[workspace]
authors = ["fkt <deepthought@postech.ac.kr>"]
channels = ["conda-forge"]
name = "scBioStat"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
quarto = ">=1.8.27,<2"
r-base = ">=4.3.0"
r-rmarkdown = "*"
r-knitr = "*"
